### ISSUE TITLE
Improvements on the Masterclass

### ISSUE THREAD

**Issue by heckelmann** [dynatrace-oss/progressiveDelivery-masterclass#82]
For the current Masterclass, we considered the following enhancements.

- [ ] Move the repository to `dynatrace-oss` organization
- [ ] Create pre-built images of the application and add them to `ghcr.io`
- [ ] Add nodejs to devcontainer
- [ ] Add flagd to devcontainer
- [ ] Create GiHub Page for the Walkthrough and Documentation
- [ ] Restructure Repository with pre-configured manifests for different walkthrough steps.
